services:
  client1:
    build: .
    deploy:
      resources:
        limits:
          cpus: '0.5'
          cpuset-cpus: '0'
          memory: 100M
    extra_hosts:
    - host.docker.internal:host-gateway
    volumes:
    - .:/client
  client2:
    build: .
    deploy:
      resources:
        limits:
          cpus: '1.0'
          cpuset-cpus: '1'
          memory: 200M
    extra_hosts:
    - host.docker.internal:host-gateway
    volumes:
    - .:/client
  client3:
    build: .
    deploy:
      resources:
        limits:
          cpus: '1.5'
          cpuset-cpus: 2,3
          memory: 500M
    extra_hosts:
    - host.docker.internal:host-gateway
    volumes:
    - .:/client
  client4:
    build: .
    deploy:
      resources:
        limits:
          cpus: '0.25'
          cpuset-cpus: '4'
          memory: 50M
    extra_hosts:
    - host.docker.internal:host-gateway
    volumes:
    - .:/client
version: '3.8'
