services:
  client1:
    build: .
    extra_hosts:
    - host.docker.internal:host-gateway
    volumes:
    - .:/client
  client2:
    build: .
    extra_hosts:
    - host.docker.internal:host-gateway
    volumes:
    - .:/client
version: '3.8'
